### ISSUE TITLE
Example typos

### ISSUE THREAD

**Issue by PedroTadim** [MonetDBSolutions/monetdbe-examples#1]
At cache.c example:

monetdbe_query(remote, "call sys.describe(\"sys\",\"lineitem\"", &schema); 

There's a closing parenthesis missing,

**Comment by PedroTadim** [comment]
On the same example.

if( remote->error || schema->error || data->error)
    error("Could not access the remote database");

The error message is only valid for the remote->error case

**Comment by PedroTadim** [comment]
Also the database is not being closed at the end.

**Comment by njnes** [comment]
This example is indeed far from ready. Most important requirement is to add
the implementation of 'remote'. ie same interface as monetdbe, but use remote calls.
Next to that the results needs to be obtained and used correctly.

**Comment by PedroTadim** [comment]
Sure, we eventually will get it done.

**Comment by njnes** [comment]
bogus example is removed.
