### ISSUE TITLE
Error using monetdbe_open() with persistency

### ISSUE THREAD

**Issue by krimp** [MonetDBSolutions/monetdbe-examples#10]
The examples indicates that in monetdbe_open() the second argument is a string for the db directory or NULL for in-memory mode.

The following inmemory works ok:

monetdbe_database db = NULL;
monetdbe_open(&db, NULL /* inmemory database */, NULL /* no options */);

However, this one (and any variants) fails:

monetdbe_open(&db,  "mydbdir/", NULL /* no options */);

Is there an example of how to open a db with persistency, or is it a bug?

**Comment by bernardom29** [comment]
To use MonetDBe with a persistent database directory, the _monetdbe_open()_ call must feature an absolute path to the database directory.

For example:
`monetdbe_open(&db, "/home/test/db_directory", NULL);`

However, this particular feature has a bug in the current release. This means that using the correct format, the _monetdbe_open()_ call returns an error message (`sabaoth not initialized`). 
Our team has noticed the bug and it is fixed in the current version. This patch will be present in the next future release. If you want the fix now, you'll have to grab the source code from our repository and use the latest version.

**Comment by krimp** [comment]
Re: "If you want the fix now, you'll have to grab the source code from our repository and use the latest version.": 

It seems like a fresh "git clone https://github.com/MonetDB/MonetDB MonetDB" + a rebuild does not do the trick? Does the source code need to be grabbed from another place?

**Comment by bernardom29** [comment]
I was indeed referring to that repo. Tried to verify that this was fixed with a fresh clone, and it works for me.

How did you rebuild MonetDB? And are you sure you used the new version and not an old one?

Did you get the error message I mentioned above (`sabaoth not initialized`) when using the correct `monetdbe_open()` syntax?

**Comment by krimp** [comment]
I followed the guide, but cloned it to a directory with another name:

git clone https://github.com/MonetDB/MonetDB MonetDBe0
cd MonetDBe0
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .

I had to remove /usr/lib/libmonetdbe.so.1 (which was from the old build) and replace it with the one from the latest build. 
Now it works.

Thank you very much for the support!

**Comment by yzchang** [comment]
Which OS do you use?

Glad it works for you now.  But manually replace a file in /usr/lib sounds like a candidate for future problems.

You've probably installed the previous MonetDB version through an official installer, so you get the libraries installed in the default locations such as /usr/lib and MonetDB binaries automatically added to your PATH?  If you want to use another MonetDB version, it'd be cleaner to install it in a different location and include that in your PATH.

**Comment by krimp** [comment]
For this test installation, I am using Linux on a RPi (4b+). 

The previous installation was not from an official installation.

When starting the application like ./myApp, the following errorMsg shows up :  'directory'/gdk/gdk_tracer.c GDKtracer_init_trace_file:122
M_CRITICAL GDK_TRACER  
main thread          
#Failed to open 'directory'/mdbtrace.log: Permission denied

Hence, I have to start the application with sudo ./myApp 

Adding path to the libraries did not work, even though 'which' found the libraries (tried add path in /etc/profile as well as in ~/.bashrc).  

sudo ./myApp gave errorMsg: error while loading shared libraries: libmonetdbe.so.1: cannot open shared object file: No such file or directory. 

By symlinking the libmonetdbe.so-files to /usr/lib, everything works ok (which I also did on the previous installation).

After including the monetdbe library in the C++ application, I have to start it like sudo ./myApp. Sudo was not necessary when using the monetdb libraries.

For the record: I am building my C++ application with make (and not cmake).

**Comment by bernardom29** [comment]
The `Failed to open 'directory'/mdbtrace.log` message was a small bug which is now fixed. If you update to the latest version, you shouldn't see that message.
You don't have to run monetdb-e with root privileges.

Did you set your LD_LIBRARY_PATH to include the directory where you have the libmonetdbe.so files? You can symlink the library to a directory where the system expects libraries (like /usr/lib), but I believe there are other better methods for the system to find our shared library.

**Comment by krimp** [comment]
The latest version does not compile without errors (RPi4B+):

/home/pi/MonetDBe/sql/storage/store.c: In function ‘store_init’:
/home/pi/MonetDBe/sql/storage/store.c:1957:18: error: conversion from ‘long long unsigned int’ to ‘long unsigned int                     ’ changes value from ‘9223372036854775808’ to ‘0’ [-Werror=overflow]
   .transaction = ATOMIC_VAR_INIT(TRANSACTION_ID_BASE),
                  ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [sql/storage/CMakeFiles/sqlstorage.dir/build.make:89: sql/storage/CMakeFiles/sqlstorage.dir/store.c.o]                      Error 1
make[1]: *** [CMakeFiles/Makefile2:3626: sql/storage/CMakeFiles/sqlstorage.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by MitchellWeg** [comment]
I have the latest version compiled on my RPi3 and it works just fine. 
What kind of CMake flags did you use?

**Comment by krimp** [comment]
I did it like recommended in the install notes:

```
git clone https://github.com/MonetDB/MonetDB MonetDBe
cd MonetDBe
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```
I also tried the latest version on a 64bit Ubuntu VM (18.04 LTS), and it compiles fine on that one. However on my RPi4B+, 32bit it does not compile. The previous version compiled fine on the RPi4B+.

**Comment by njnes** [comment]
the ATOMIC_TYPE seems to be a 32 bit int on the RPi4B+, where on the 64 bit linux systems the ATOMIC_TYPE is 64 bit. We are working on a dynamic type based on the native int size too solve this issue.

**Comment by njnes** [comment]
It should now be possible to use a relative directory as well.
