### ISSUE TITLE
Missing monetdbe_listen() in monetdbe.h

### ISSUE THREAD

**Issue by krimp** [MonetDBSolutions/monetdbe-examples#9]
In the myserver.c there is a call to monetdbe_listen(). However the monetdbe_listen() is not defined in monetdbe.h.

Further, there is a call to  monetdb_error(). I guess that should be  monetdb**e**_error()...

**Comment by njnes** [comment]
Your right the monetdbe_listen isn't implemented currently.

**Comment by njnes** [comment]
we have a different solutions now, ie we pass (usock or port) via an mapi_server struct in the monetdbe_open options argument.
See also new example proxy.c
